server:
  port: 8081
  servlet:
    context-path: /micromarket

spring:
  datasource:
    data-username: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.105.78.64:3306/micromarket?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

